### ISSUE TITLE
SP1-2 project proposal writing (technologies required and project design section)

### ISSUE THREAD

**Issue by pardeshiamitsingh** [litpuvn/cheapride#4]

**Comment by pardeshiamitsingh** [comment]
- Section under project design is not with the flow.
- example - under project design ,there are sections which are user characteristics which looks odd. create separate section for it.
- I feel under design section there should be UI design , project architecture design etc.
-

**Comment by litpuvn** [comment]
@Dian: Can you copy my "User Characteristics" section to "Requirement" section of yours?
